---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder

inputs:
  - name: published-stemcell-bionic
  - name: bosh-linux-stemcell-builder-master

run:
  path: bosh-linux-stemcell-builder-master/ci/xenial/tasks/notify-new-stemcell-version-bionic.sh
